import{d as f,o as d,c as g,a,A as b,S as $,u as P,r as z,e as v,f as E,H as D,h,w as p,v as m,g as c,x as O,n as u,af as x,t as w}from"./cyCOdGck.js";import{_ as j}from"./CAC1Cd_U.js";import{_ as A}from"./BgBr2OJl.js";import{u as _}from"./sRUYLMiV.js";const G=""+new URL("portrait2landscape.7nGEd4E6.png",import.meta.url).href,R={key:0,class:"image-container"},V=f({__name:"CardIcon",props:{orientationMode:{type:String,required:!0}},setup(i){const t=i;return(e,o)=>t.orientationMode==="LANDSCAPE"?(d(),g("div",R,o[0]||(o[0]=[a("div",null,[a("img",{src:G,alt:"landscape",class:"relative z-10"})],-1)]))):b("",!0)}}),U=$(V,[["__scopeId","data-v-add01827"]]),H={class:"absolute -top-[12px] left-[4px] p-[6px] z-10"},q={class:"absolute top-0 right-0 p-[6px] z-10"},Q=["alt","src"],Z=["alt","src"],J=f({__name:"Card",props:{src:{type:String,default:""},alt:{type:String,default:_("whitelogo.png")},size:{type:String,default:P().public.CONSTANTS.THUMBNAIL_DEFAULT_SIZE},isSpinnerExist:{type:Boolean,default:!0},isFavorite:{type:Boolean,default:!1},orientationMode:{type:String,default:"PORTRAIT"}},setup(i,{expose:t}){const e=i,o=z({isPending:!0,onLoadEvts:s=>{},isActive:!1}),n=v(),r=v(),y=()=>{o.isActive=!0},k=()=>{o.isActive=!1},L=()=>{n.value&&(o.isPending=!0,n.value.onload=()=>{n.value&&(n.value.style.setProperty("width",e.size,"important"),n.value.style.setProperty("height",e.size,"important"),o.isPending=!1,o.onLoadEvts(n.value.src))},n.value.src=e.src)},T=s=>{var l;(l=n.value)!=null&&l.src&&s(n.value.src),o.onLoadEvts=s},B=()=>{var s;return(s=n.value)==null?void 0:s.src},C=()=>{r.value&&r.value.animFavoritePerform()},F=()=>{r.value&&r.value.animFavoritePerformShake()};return E(async()=>{await D(),L()}),t({setQueueLoadEvt:T,getImgSrc:B,animShine:y,animFavoritePerform:C,animFavoritePerformShake:F}),(s,l)=>{const I=U,M=j,N=A;return d(),g("div",{class:u(`
            flex items-center justify-center
            rounded-3xl
            !w-[${e.size}] min-w-[${e.size}]
            !h-[${e.size}] min-h-[${e.size}]
        `)},[a("div",H,[h(I,{orientationMode:e.orientationMode},null,8,["orientationMode"])]),p(a("div",{class:u(["efx-3d rounded-3xl relative",{active:c(o).isActive}]),onAnimationend:k},[a("div",q,[e.isFavorite?(d(),O(M,{key:0,ref_key:"$favoriteBtn",ref:r,isSelected:!0},null,512)):b("",!0)]),a("img",{ref_key:"$img",ref:n,alt:e.alt,src:e.src||("usePublic"in s?s.usePublic:c(_))("whitelogo.png"),class:u(`
                    object-fill aspect-1
                    w-[${e.size}]
                    h-[${e.size}]
                    rounded-3xl
                `)},null,10,Q)],34),[[m,!c(o).isPending]]),p(a("div",{style:x(`width:${e.size} !important; height:${e.size} !important;`)},[a("img",{alt:e.alt,src:("usePublic"in s?s.usePublic:c(_))("whitelogo.png"),class:u(`
                    object-fill aspect-1
                    rounded-3xl opacity-60
                `),style:x(`width:${e.size} !important; height:${e.size} !important;`)},null,12,Z),p(h(N,{w:10,h:10,class:u(`
                    relative
                    -top-[50%]
                    left-[50%]
                    -translate-x-[20px] -translate-y-[20px]
                `)},null,512),[[m,e.isSpinnerExist]])],4),[[m,c(o).isPending]]),l[0]||(l[0]=a("span",{class:"sr-only"},"thumbnail",-1))],2)}}}),oe=$(J,[["__scopeId","data-v-e69811ed"]]),K={role:"status",class:"flex flex-col justify-center items-center my-auto"},W={class:"sr-only"},ne=f({__name:"SpinnerTxt",props:{w:{default:4},h:{default:4},color:{default:"gray-200"},txt:{default:""},expoTxt:{default:"Loading..."}},setup(i){const t=i;return(e,o)=>{const n=A;return d(),g("div",K,[h(n,{w:t.w,h:t.h,color:t.color},null,8,["w","h","color"]),p(a("div",{class:"mt-2"},w(t.txt),513),[[m,t.txt]]),a("span",W,w(t.expoTxt),1)])}}}),S="display:block; margin-left:auto; margin-right:auto;",se=f({__name:"Adsense",props:{slot:{default:""},format:{default:"auto"},layout:{default:""}},setup(i){const{DEV:t,GOOGLE:e}=P().public,o=`${S} padding-top:auto; padding-bottom:auto; text-align:center; background-color:burlywood; border-color:red; border-width:thin; border-radius:5px; opacity:0.8;`;z({style:t?o:S});const n=v();return E(()=>{setTimeout(()=>{n.value;try{(window.adsbygoogle=window.adsbygoogle||[]).push({}),window.googletag=window.googletag||{cmd:[]}}catch{}},1)}),(r,y)=>(d(),g("div"))}}),ae=async(i,t="")=>t||(i?i.replace("index.html","thumbnail.png"):_("whitelogo.png"));export{oe as _,ne as a,se as b,ae as u};
